version: '3.8'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://172.17.0.1:12201"
 
services:
  openldap:
    <<: *default-opts
    env_file:
      .env
    image: osixia/openldap:${OPEN_LDAP_TAG}
    volumes:
      - ldap_database:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    secrets:
      - ldap_admin_password
      - ldap_config_password
      - ldap_ro_user_password
    environment:
      - LDAP_TLS=false
      - LDAP_ADMIN_PASSWORD_FILE=/run/secrets/ldap_admin_password
      - LDAP_CONFIG_PASSWORD_FILE=/run/secrets/ldap_config_password
      - LDAP_READONLY_USER_PASSWORD_FILE=/run/secrets/ldap_ro_user_password
    networks:
      - ldap_network
    ports:
      - "389:389"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  openldap-admin:
    <<: *default-opts
    image: osixia/phpldapadmin:${LDAP_ADMIN_TAG}
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    networks:
      - ldap_network
      - proxy_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.ldap-admin.entrypoints: ${ADMIN_ENTRYPOINT:-websecure}
        traefik.http.routers.ldap-admin.rule: Host(`${ADMIN_DOMAIN:-ldap-admin.host.local}`)
        traefik.http.routers.ldap-admin.service: ldap-admin
        traefik.http.services.ldap-admin.loadbalancer.server.port: 80

  openldap-ssp:
    <<: *default-opts
    image: ltbproject/self-service-password:${SELF_SERVICE_PASSWORD_TAG}
    networks:
      - ldap_network
      - proxy_network
    configs:
      - source: ssp_config
        target: /var/www/conf/config.inc.local.php
    secrets:
      - ldap_admin_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.ldap-ssp.entrypoints: ${SSP_ENTRYPOINT:-websecure}
        traefik.http.routers.ldap-ssp.rule: Host(`${SSP_DOMAIN:-ssp.host.local}`)
        traefik.http.routers.ldap-ssp.service: ldap-ssp
        traefik.http.services.ldap-ssp.loadbalancer.server.port: 80

  openldap-backup:
    <<: *default-opts
    image: osixia/openldap-backup:${OPEN_LDAP_TAG}
    volumes:
      - ldap_database:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_backup:/data/backup
    environment:
      - LDAP_BACKUP_TTL=14
      - LDAP_BACKUP_CONFIG_CRON_EXP=0 4 * * *
      - LDAP_BACKUP_DATA_CRON_EXP=0 4 * * *
    networks:
      - ldap_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  ldap_admin_password:
    external: true
  ldap_config_password:
    external: true
  ldap_ro_user_password:
    external: true

configs:
  ssp_config:
    file: ./.ssp.conf.php
    name: ssp-conf-1
      
networks:
  ldap_network:
    driver: overlay

  proxy_network:
    external: true

volumes:
  ldap_database:
    driver: local
    driver_opts:
      device: ${HOST_LDAP_DATABASE}
      type: none
      o: bind
      # device: ":${HOST_LDAP_DATABASE?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  ldap_config:
    driver: local
    driver_opts:
      device: ${HOST_LDAP_CONFIG}
      type: none
      o: bind
      # device: ":${HOST_LDAP_CONFIG?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  ldap_backup:
    driver: local
    driver_opts:
      device: ${HOST_LDAP_BACKUP}
      type: none
      o: bind
      # device: ":${HOST_LDAP_BACKUP?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1