version: '3.9'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://172.17.0.1:12201"
 
services:
  xwiki:
    <<: *default-opts
    image: xwiki:${XWIKI_TAG}
    volumes:
      - data:/usr/local/xwiki
    secrets:
      - mariadb_db_user
      - mariadb_db_password
      - mariadb_db_database
    environment:
      - DB_USER_FILE=/run/secrets/mariadb_db_user
      - DB_PASSWORD_FILE=/run/secrets/mariadb_db_password
      - DB_DATABASE_FILE=/run/secrets/mariadb_db_database
    networks:
      - proxy_network
      - mariadb_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.xwiki.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.xwiki.rule: Host(`${DOMAIN:-xwiki.host.local}`)
        traefik.http.routers.xwiki.service: xwiki
        traefik.http.services.xwiki.loadbalancer.server.port: 8080

  backup:
    <<: *default-opts
    image: "alpine:latest"
    volumes:
      - data:/usr/local/xwiki
      - backup:/usr/local/xwiki/backup
    command:
      - sh
      - -c
      - | 
        echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup service started. First data backup will be executed in $$BACKUP_FREQUENCY.";
        while true; do
          sleep $$BACKUP_FREQUENCY;
          data_dir=/usr/local/xwiki/data;
          backup_dir=/usr/local/xwiki/backup;
          mkdir -p $$backup_dir;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Creating config files backup...";
          tar -C $$data_dir -cvzf $$backup_dir/xwiki_config_backup_$$(date +'%Y%m%d_%H%M%S').tar.gz xwiki.cfg xwiki.properties hibernate.cfg.xml
          find $$backup_dir -iname "xwiki_config_backup_*.tar.gz" -mtime +$$RETENTION_DAYS -exec rm -rf {} \;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup completed. Next backup in $$BACKUP_FREQUENCY.";
        done
    deploy:
      restart_policy:
        condition: on-failure
        delay: 600s

secrets:
  mariadb_db_database:
    external: true
  mariadb_db_user:
    external: true
  mariadb_db_password:
    external: true
      
networks:
  proxy_network:
    external: true

  mariadb_network:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      device: ${HOST_XWIKI_DATA}
      type: none
      o: bind

  backup:
    driver: local
    driver_opts:
      device: ${HOST_XWIKI_BACKUP}
      type: none
      o: bind