version: '3.9'
 
services:
  nextcloud:
    image: nextcloud
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud_apps:/var/www/html/custom_apps
    secrets:
      - mariadb_db_password
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mariadb_db_password
    networks:
      - mariadb_network
    ports:
      - 9090:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      # labels:
      #   traefik.enable: "true"
      #   traefik.http.routers.nextcloud.entrypoints: web
      #   traefik.http.routers.nextcloud.rule: Host(`${EXTERNAL_DOMAIN?Variable not set}`)
      #   traefik.http.routers.nextcloud.service: nextcloud
      #   traefik.http.services.nextcloud.loadbalancer.server.port: 80

secrets:
  mariadb_db_password:
    external: true
      
networks:
  mariadb_network:
    external: true

volumes:
  nextcloud_data:
    driver: local
    driver_opts:
      device: ${HOST_NEXTCLOUD_DATA}
      type: none
      o: bind

  nextcloud_apps:
    driver: local
    driver_opts:
      device: ${HOST_NEXTCLOUD_APPS}
      type: none
      o: bind