version: '3.9'
 
services:
  nextcloud:
    image: nextcloud
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
    secrets:
      - nextcloud_admin_user
      - nextcloud_admin_password
      - mariadb_db_database
      - mariadb_db_user
      - mariadb_db_password
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE_FILE=/run/secrets/mariadb_db_database
      - MYSQL_USER_FILE=/run/secrets/mariadb_db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mariadb_db_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
    networks:
      - mariadb_network
    ports:
      - 9090:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      # labels:
      #   traefik.enable: "true"
      #   traefik.http.routers.nextcloud.entrypoints: web
      #   traefik.http.routers.nextcloud.rule: Host(`${EXTERNAL_DOMAIN?Variable not set}`)
      #   traefik.http.routers.nextcloud.service: nextcloud
      #   traefik.http.services.nextcloud.loadbalancer.server.port: 80

secrets:
  nextcloud_admin_user:
    external: true
  nextcloud_admin_password:
    external: true
  mariadb_db_database:
    external: true
  mariadb_db_user:
    external: true
  mariadb_db_password:
    external: true
      
networks:
  mariadb_network:
    external: true

volumes:
  nextcloud_data:
    driver: local
    driver_opts:
      device: ${HOST_NEXTCLOUD_DATA}
      type: none
      o: bind

  nextcloud_apps:
    driver: local
    driver_opts:
      device: ${HOST_NEXTCLOUD_APPS}
      type: none
      o: bind

  nextcloud_config:
    driver: local
    driver_opts:
      device: ${HOST_NEXTCLOUD_CONFIG}
      type: none
      o: bind