version: '3.9'

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://127.0.0.1:12201"

services:
  jenkins:
    <<: *default-opts
    image: jenkins/jenkins:${JENKINS_TAG}
    networks:
      - proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins_data:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.jenkins.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.jenkins.rule: Host(`${DOMAIN:-jenkins.localhost}`)
        traefik.http.routers.jenkins.service: jenkins
        traefik.http.services.jenkins.loadbalancer.server.port: 8080

networks:
  proxy_network:
    external: true

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      device: ${HOST_JENKINS_DATA}
      type: none
      o: bind
      # device: ":${HOST_JENKINS_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1
