version: '3.8'
 
services:
  db:
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - mariadb_db_database
      - mariadb_db_user
      - mariadb_db_password
      - mariadb_root_password
    environment:
      - MARIADB_DATABASE_FILE=/run/secrets/mariadb_db_database
      - MARIADB_USER_FILE=/run/secrets/mariadb_db_user
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_db_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    command: 
      - mysqld
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_allowed_packet=256M
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW
      - --innodb-read-only-compressed=OFF
    networks:
      - mariadb_network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

secrets:
  mariadb_db_database:
    external: true
  mariadb_db_user:
    external: true
  mariadb_db_password:
    external: true
  mariadb_root_password:
    external: true 
      
networks:
  mariadb_network:
    external: true

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: ${HOST_MARIADB_DATA}
      type: none
      o: bind
      # device: ":${HOST_MARIADB_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1