version: '3.8'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://172.17.0.1:12201"
 
services:
  db:
    <<: *default-opts
    image: mariadb:${MARIADB_TAG}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./entrypoint.d:/docker-entrypoint-startdb.d:ro
    secrets:
      - mariadb_db_database
      - mariadb_db_user
      - mariadb_db_password
      - mariadb_root_password
    environment:
      - MARIADB_DATABASE_FILE=/run/secrets/mariadb_db_database
      - MARIADB_USER_FILE=/run/secrets/mariadb_db_user
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_db_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    command: 
      - mysqld
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_allowed_packet=256M
      - --transaction-isolation=READ-COMMITTED
      - --max_connections=1000
      - --binlog-format=ROW
      - --innodb-read-only-compressed=OFF
    networks:
      - mariadb_network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  db-backup:
    <<: *default-opts
    image: mariadb:${MARIADB_TAG}
    volumes:
      - mariadb_backup:/backup
    secrets:
      - mariadb_root_password
    command: 
      - sh
      - -c
      - | 
        echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup service started. First dump will be executed in $$BACKUP_FREQUENCY.";
        while true; do
          sleep $$BACKUP_FREQUENCY;
          DB_PASSWORD=$$(cat /run/secrets/mariadb_root_password);
          backup_dir=/backup;
          mkdir -p $$backup_dir;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Creating SQL dump of $$DB_NAME database...";
          /usr/bin/mariadb-dump -u root --password=$$DB_PASSWORD --host=db --all-databases --no-tablespaces > $$backup_dir/db_$$(date +'%Y%m%d_%H%M%S').sql;
          find $$backup_dir -iname "db_*.sql" -mtime +$$RETENTION_DAYS -exec rm -rf {} \;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup completed. Next dump in $$BACKUP_FREQUENCY.";
        done
    networks:
      - mariadb_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 600s

secrets:
  mariadb_db_database:
    external: true
  mariadb_db_user:
    external: true
  mariadb_db_password:
    external: true
  mariadb_root_password:
    external: true 
      
networks:
  mariadb_network:
    external: true

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: ${HOST_MARIADB_DATA}
      type: none
      o: bind
      # device: ":${HOST_MARIADB_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  mariadb_backup:
    driver: local
    driver_opts:
      device: ${HOST_MARIADB_BACKUP}
      type: none
      o: bind
      # device: ":${HOST_MARIADB_BACKUP?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1