version: '3.8'

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"

services:
  error-pages:
    <<: *default-opts
    image: tarampampam/error-pages:${TAG}
    environment:
      TEMPLATE_NAME: l7-dark
    networks:
      - proxy_network
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.error-pages-router.priority: 10
        traefik.http.routers.error-pages-router.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.error-pages-router.rule: HostRegexp(`{host:.+}`)
        traefik.http.routers.error-pages-router.service: error-pages-service
        traefik.http.services.error-pages-service.loadbalancer.server.port: 8080

        # "error-pages-middleware" settings
        traefik.http.routers.error-pages-router.middlewares: error-pages-middleware
        traefik.http.middlewares.error-pages-middleware.errors.status: 400-599
        traefik.http.middlewares.error-pages-middleware.errors.service: error-pages-service
        traefik.http.middlewares.error-pages-middleware.errors.query: /{status}.html

networks:
  proxy_network:
    external: true
