version: "3.9"

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://172.17.0.1:12201"

services:
  gitlab:
    <<: *default-opts
    image: gitlab/gitlab-ce:${GITLAB_TAG}
    networks:
      - gitlab_network
      - proxy_network
      - metrics_network
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.gitlab.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.gitlab.rule: Host(`${DOMAIN:-gitlab.localhost}`)
        traefik.http.routers.gitlab.service: gitlab
        traefik.http.services.gitlab.loadbalancer.server.port: 80

configs:
  gitlab:
    file: ./.rb

secrets:
  gitlab_root_password:
    external: true
      
networks:
  gitlab_network:
    driver: overlay
    attachable: true

  proxy_network:
    external: true

  metrics_network:
    external: true

volumes:
  gitlab_data:
    driver: local
    driver_opts:
      device: ${HOST_GITLAB_DATA}
      type: none
      o: bind
      # device: ":${HOST_GITLAB_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  gitlab_config:
    driver: local
    driver_opts:
      device: ${HOST_GITLAB_CONFIG}
      type: none
      o: bind
      # device: ":${HOST_GITLAB_CONFIG?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  gitlab_logs:
    driver: local
    driver_opts:
      device: ${HOST_GITLAB_LOGS}
      type: none
      o: bind
      # device: ":${HOST_GITLAB_LOGS?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1