global:
  resolve_timeout: 1m

  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'Alertmanager <alertmanager@example.com>'

route:
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'yourmail@example.com' 
    from: 'alertmanager@example.com'
    require_tls: false
    send_resolved: true