global:
  resolve_timeout: 1m

  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.example.com:587'
  smtp_auth_username: user
  smtp_auth_password: password
  smtp_require_tls: true

route:
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'yourmail@example.com' 
    from: 'Alertmanager <alertmanager@example.com>'
    send_resolved: true