version: '3.8'

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"

services:
  whoami:
    <<: *default-opts
    image: "traefik/whoami"
    networks:
      - public_network
    deploy:
      mode: replicated
      replicas: 3
      labels:
        traefik.enable: "true"
        traefik.http.routers.whoami.entrypoints: ${ENTRYPOINT:-intsecure}
        traefik.http.routers.whoami.rule: Host(`${DOMAIN:-whoami.localhost}`)
        traefik.http.routers.whoami.service: whoami
        traefik.http.services.whoami.loadbalancer.server.port: 80

        # traefik.http.services.whoami.loadBalancer.sticky.cookie: "true"
        # traefik.http.services.whoami.loadBalancer.sticky.cookie.name: "sticky_whoami"

        # traefik.http.routers.wordpress.middlewares: header-ratelimiter@docker
        # traefik.http.middlewares.header-ratelimiter.ratelimit.average: 20
        # traefik.http.middlewares.header-ratelimiter.ratelimit.period: 1s
        # traefik.http.middlewares.header-ratelimiter.ratelimit.burst: 50
        # traefik.http.middlewares.header-ratelimiter.ratelimit.sourcecriterion.requestheadername: HEADER-NAME

networks:
  public_network:
    external: true
