x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"

services:
  ollama:
    <<: *default-opts
    image: ollama/ollama:${OLLAMA_TAG:-latest}
    volumes:
      - ollama_data:/root/.ollama
      - ollama_input:/input
    ports:
      - ${OLLAMA_WEBAPI_PORT:-11434}:11434
    networks:
      - ollama_network
      - proxy_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.ollama.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.ollama.rule: Host(`${OLLAMA_DOMAIN:-ollama.host.local}`)
        traefik.http.routers.ollama.service: ollama
        traefik.http.services.ollama.loadbalancer.server.port: 11434


networks:
  ollama_network:
    driver: overlay
    attachable: true
  
  proxy_network:
    external: true

volumes:
  ollama_data:
    driver: local
    driver_opts:
      device: ${HOST_OLLAMA_DATA}
      type: none
      o: bind
  
  ollama_input:
    driver: local
    driver_opts:
      device: ${HOST_OLLAMA_INPUT}
      type: none
      o: bind