version: '3.9'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://127.0.0.1:12201"

services:
  prometheus:
    <<: *default-opts
    image: prom/prometheus:${PROMETHEUS_TAG}
    ports:
      - 9999:9090
    volumes:
      - prometheus_data:/etc/prometheus
    networks:
      - metrics_network
    command:
      - --config.file=/etc/prometheus/prometheus-config.yml
      - --web.enable-lifecycle
    deploy:
      mode: replicated
      replicas: 1

  node-exporter:
    image: prom/node-exporter:v1.3.1
    networks:
      - metrics_network
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename:ro
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    <<: *default-opts
    image: grafana/grafana-oss:${GRAFANA_TAG}
    ports:
      - 8003:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - metrics_network
    deploy:
      mode: replicated
      replicas: 1

networks:
  metrics_network:
    external: true

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      device: ${HOST_PROMETHEUS_DATA}
      type: none
      o: bind
      # device: ":${HOST_PROMETHEUS_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  grafana_data:
    driver: local
    driver_opts:
      device: ${HOST_GRAFANA_DATA}
      type: none
      o: bind
      # device: ":${HOST_GRAFANA_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1