version: '3.8'

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://127.0.0.1:12201"

services:
  agent:
    <<: *default-opts
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: 
          - node.platform.os == linux

  portainer:
    <<: *default-opts
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - agent_network
      - public_network
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
    ports:
      - "8000:9000"

networks:
  public_network:
    external: true
  agent_network:
    driver: overlay

volumes:
  portainer_data:
    driver: local
    driver_opts:
      device: ${HOST_PORTAINER_PATH}
      type: none
      o: bind
      # device: ":${HOST_PORTAINER_PATH?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1