version: '3.8'

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://172.17.0.1:12201"

services:
  reverse-proxy:
    <<: *default-opts
    image: traefik:${TRAEFIK_TAG}
    command: 
      - --log
      - --log.level=INFO
      - --log.filePath=/data/traefik.log
      - --accesslog
      - --accesslog.filePath=/data/access.log

      # Dashboard config
      - --api.dashboard=true
      - --api.insecure=true

      # Provider configuration
      - --providers.docker.watch=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmModeRefreshSeconds=15
      - --providers.docker.network=proxy_network
      - --providers.docker.endpoint=unix:///var/run/docker.sock

      - --providers.file.watch=true
      - --providers.file.directory=/data/dynamic/

      # Entry points configuration
      ## web and websecure
      - --entryPoints.web.address=:80
      ## https redirection and configuration
      # - --entryPoints.web.http.redirections.entryPoint.to=websecure
      # - --entryPoints.web.http.redirections.entryPoint.scheme=https
      # - --entryPoints.web.http.redirections.entrypoint.permanent=true

      # - --entryPoints.websecure.address=:443
      # - --entryPoints.websecure.http.middlewares=websecure-entrypoint-chain@file

      # Certificate configuration
      ## LetsEncrypt
      # - --entryPoints.websecure.http.tls.certResolver=letsencrypt
      # - --certificatesResolvers.letsencrypt.acme.email=${LE_ACME_EMAIL?Variable not set}
      # - --certificatesResolvers.letsencrypt.acme.storage=/data/acme.json
      # - --certificatesResolvers.letsencrypt.acme.keyType=EC384
      # - --certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web

      ## DNS Challenge (provider agnostic)
      # - --entryPoints.websecure.http.tls.domains[0].main=${EXTERNAL_DOMAIN?Variable not set}
      # - --entryPoints.websecure.http.tls.domains[0].sans=*.${EXTERNAL_DOMAIN?Variable not set}
      # - --entryPoints.websecure.http.tls.domains[1].main=${INTERNAL_DOMAIN?Variable not set}
      # - --entryPoints.websecure.http.tls.domains[1].sans=*.${INTERNAL_DOMAIN?Variable not set}

      ## DNS Challenge (Linode)
      # - --entryPoints.websecure.http.tls.certResolver=linode-dnschallenge
      # - --certificatesResolvers.linode-dnschallenge.acme.dnschallenge=true
      # - --certificatesResolvers.linode-dnschallenge.acme.dnschallenge.provider=linode
      # - --certificatesResolvers.linode-dnschallenge.acme.email=${LE_ACME_EMAIL?Variable not set}
      # - --certificatesResolvers.linode-dnschallenge.acme.storage=/data/acme.json

      ## DNS Challenge (allinkl)
      # - --entryPoints.websecure.http.tls.certResolver=allinkl-dnschallenge
      # - --certificatesResolvers.allinkl-dnschallenge.acme.dnschallenge=true
      # - --certificatesResolvers.allinkl-dnschallenge.acme.dnschallenge.provider=allinkl
      # - --certificatesResolvers.allinkl-dnschallenge.acme.email=${LE_ACME_EMAIL?Variable not set}
      # - --certificatesResolvers.allinkl-dnschallenge.acme.storage=/data/acme.json

      ## DNS Challenge (hetzner)
      # - --entryPoints.websecure.http.tls.certResolver=hetzner-dnschallenge
      # - --certificatesResolvers.hetzner-dnschallenge.acme.dnschallenge=true
      # - --certificatesResolvers.hetzner-dnschallenge.acme.dnschallenge.provider=hetzner
      # - --certificatesResolvers.hetzner-dnschallenge.acme.email=${LE_ACME_EMAIL?Variable not set}
      # - --certificatesResolvers.hetzner-dnschallenge.acme.storage=/data/acme.json

      # Prometheus configuration
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.entryPoint=metrics
      - --entryPoints.metrics.address=:8082

    ## Linode secrets
    # secrets:
    #   - linode_dns_token
    # environment:
    #   - LINODE_TOKEN_FILE=/run/secrets/linode_dns_token

    ## all-inkl secrets
    # secrets:
    #   - all_inkl_login
    #   - all_inkl_password
    # environment:
    #   - ALL_INKL_LOGIN_FILE=/run/secrets/all_inkl_login
    #   - ALL_INKL_PASSWORD_FILE=/run/secrets/all_inkl_password

    ## Hetzner secrets
    # secrets:
    #   - hetzner_dns_token
    # environment:
    #   - HETZNER_API_KEY_FILE=/run/secrets/hetzner_dns_token
    
    networks:
      - proxy_network
      - metrics_network
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - traefik_data:/data
    deploy:
      placement:
        constraints: 
          - node.role == manager
      update_config:
        delay: 10s
        order: start-first
        parallelism: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.traefik.entrypoints: ${TRAEFIK_ENTRYPOINT:-websecure}
        traefik.http.routers.traefik.rule: Host(`${TRAEFIK_DOMAIN:-traefik.host.local}`)
        traefik.http.routers.traefik.service: traefik
        traefik.http.services.traefik.loadbalancer.server.port: 8080

networks:
  proxy_network:
    external: true

  metrics_network:
    external: true

## Linode secrets
# secrets:
#   linode_dns_token:
#     external: true

## all-inkl secrets
# secrets:
#   all_inkl_login:
#     external: true
#   all_inkl_password:
#     external: true

## Hetzner secrets
# secrets:
#   hetzner_dns_token:
#     external: true

volumes:
  traefik_data:
    driver: local
    driver_opts:
      device: ${HOST_TRAEFIK_PATH}
      type: none
      o: bind
      # device: ":${HOST_TRAEFIK_PATH?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1