version: '3.9'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"

services:
  pihole:
    <<: *default-opts
    image: pihole/pihole:${PIHOLE_TAG}
    volumes:
      - pihole_data:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    secrets:
      - pihole_webpassword
    environment:
      - WEBPASSWORD_FILE=/run/secrets/pihole_webpassword
    networks:
      - pihole
      - proxy_network
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.pihole.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.pihole.rule: Host(`${DOMAIN:-pihole.localhost}`)
        traefik.http.routers.pihole.service: pihole
        traefik.http.services.pihole.loadbalancer.server.port: 80

secrets:
  pihole_webpassword:
    external: true

volumes:
  pihole_data:
    driver: local
    driver_opts:
      device: ${HOST_PIHOLE_DATA}
      type: none
      o: bind

  pihole_dnsmasq:
    driver: local
    driver_opts:
      device: ${HOST_PIHOLE_DNSMASQ}
      type: none
      o: bind

networks:
  pihole:
  proxy_network:
    external: true
