version: "3.9"

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://127.0.0.1:12201"

services:
  nexus:
    <<: *default-opts
    image: ${NEXUS_IMAGE}:${NEXUS_TAG}
    networks:
      - nexus_network
    volumes:
      - nexus_data:/nexus-data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.nexus.entrypoints: websecure
        traefik.http.routers.nexus.rule: Host(`${EXTERNAL_DOMAIN?Variable not set}`)
        traefik.http.routers.nexus.service: nexus
        traefik.http.services.nexus.loadbalancer.server.port: 8081

networks:
  nexus_network:
    driver: overlay

volumes:
  nexus_data:
    driver: local
    driver_opts:
      device: ${HOST_NEXUS_DATA}
      type: none
      o: bind
      # device: ":${HOST_NEXUS_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1