version: '3.9'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"

services:
  logrotate:
    <<: *default-opts
    image: blacklabelops/logrotate:${TAG}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        order: stop-first
    volumes:
      - traefik_log_path:/var/log/traefik

volumes:
  traefik_log_path:
    driver: local
    driver_opts:
      device: ${TRAEFIK_LOG_PATH}
      type: none
      o: bind